apiVersion: apps/v1
kind: Deployment
metadata:
  name: poll
spec:
  replicas: 2
  selector:
    matchLabels:
      app: poll
  template:
    metadata:
      labels:
        app: poll
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchLabels:
                  app: poll
              topologyKey: kubernetes.io/hostname
      containers:
        - name: poll
          image: epitechcontent/t-dop-600-poll:k8s
          ports:
            - containerPort: 80
          env:
            - name: REDIS_HOST
              value: redis
            - name: REDIS_PORT
              value: "6379"
